### ISSUE TITLE
get rid of ServiceLoader

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#13]
See #25 for the discussion

**Comment by robstoll** [comment]
A bit more information about the implications:
- the dependencies between the modules will be more coupled (ServiceLoader is very loosly coupled) which means, one module does not only have to know the API of another module but also needs a way to get the implementation => I suggest we use only factory methods and never the implementations directly, this will allow us to exchange the implementation if required.
- it does no longer make sense to separate API and implementation in two modules or rather it is no longer possible as both would need a reference on the other module. We could of course go with 3 modules: `impl` -> `api` and a third one `factory` which has a dependency on both. However, we want to reduce the complexity.. something which needs to be discussed.
- default implementations will always be part of the classpath (unless someone uses Protractor or the like)
-  `get rid of ServiceLoader` (or dependency injection in general) means: providing an alternative implementation has to be done via configuration rather than dependency injection.
- we should not export implementations in the API (otherwise it is part of the API) which means reuse of the implementation is no longer possible and we should make them `internal` for people using an older version than jdk9 so that they cannot access the implementation => alternatively we could export also the impl and just make a note for the user that impl can always change without prior notice and backward compatibility guarantees.


# To be discussed
- one module (e.g. core) or three modules (core-api, core-impl, core-factory)?
- in case of one module: do we want to export the implementation?

**Comment by jGleitz** [comment]
> we should not export implementations in the API (otherwise it is part of the API) **which means reuse of the implementation is no longer possible**

Other implementors can still reuse existing implementations through composition via the atrium-API, can’t they?

(Arguably dumb) example: I want to create an implementation of `Path#isReadable` that does not fail if the file does not exist. So I first check whether the file exists, and if it does, I delegate to the existing implementation of `isReadable` via the atrium-API. Thereby, I reuse the existing implementation.

Any close integration with atrium’s implementation would effectively make the implementation public API and we could not change it without breaking other implementations. So from my point of view, I would answer 

> in case of one module: do we want to export the implementation?

with a clear **no**. Am I missing something?

> one module (e.g. core) or three modules (core-api, core-impl, core-factory)?

Can you elaborate on that? I am not sure which design goal you try to fulfill by splitting the core into modules.

**Comment by robstoll** [comment]
> with a clear no. Am I missing something?

Your example should still work also with one module and hidden implementation. I am thinking about things like one wants to implement an own AtriumErrorAdjuster and would like to reuse `FilterAtriumErrorAdjuster` 
if we have one module and hide the implementation, then one cannot reuse it. Alternatively we do not hide the implementation and it's the consumers responsibility to know that types in `impl` packages should be used with care. But the risk that one uses an `impl` accidentally is there.
If we have three modules, then we can hide the implementation (a user consumes only factory + api) but one can still depend on impl explicitly and reuse the impl (with the same risk that there is no backward guarantee).

I think it will be a rare case that someone is reusing abstract `impl` classes, hence I would go for one module + hide implementation for now, we can still open up things later on if really required.

**Comment by robstoll** [comment]
We already started to transition away with 0.13.0, last things should be away with 0.14.0 and either with 0.14.0 or 0.15.0 we  will present the new way how one can exchange implementations.

**Comment by robstoll** [comment]
done
