### ISSUE TITLE
switch to new MPP Plugin

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#14]
We use currently the old mop plugin system. I think most bugs which hindered Atrium to switch are now fixed.

**Comment by robstoll** [comment]
if we do this then the jdk8/kotlin1.3 extensions are most likely implemented as multiplatform module and therefore I think the package would change; the suffix jdk8 would be removed. Thus a breaking change

**Comment by jGleitz** [comment]
I think we should put this breaking change on the roadmap:

```
The 'org.jetbrains.kotlin.platform.*' plugins are deprecated and will no longer be available in Kotlin 1.4.
Please migrate the project to the 'org.jetbrains.kotlin.multiplatform' plugin.
See: https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html
```

**Comment by robstoll** [comment]
Good to know, thanks for the information

**Comment by robstoll** [comment]
done
