### ISSUE TITLE
Discussion: Rethink Domain Builders

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium-roadmap#25]
Atrium contains the builder projects, which to my understanding serve as a bridge between the domain-api and the domain implementation (i.e. domain-robstoll). The builder projects consist mainly of delegating classes (see below).

I think that this architecture can be improved, an see several possibilities to do so. The goal of this issue is to start a discussion about that. I have only recently started working on atrium and am not aware of the many, many considerations that have obviously gone into the codebase. It is likely that the response to this discussion will be “I know the arguments, the current solution is the best one”. And this is absolutely fine. I nevertheless want to discuss. Because best case, we can improve the code. And worst case, I (and maybe others) learn something about atrium.

## Do we need dependency inversion?

Uncle Bob defines dependency inversion as:

> A. High-level modules should not depend upon low-level modules. Both should depend upon abstractions.

> B. Abstractions should not depend upon details. Details should depend upon abstractions.

To my understanding, this is the architectural intend in the separation of domain-api, domain-builders and domain-robstoll.

_However_ I cannot see any real advantage of this pattern here. Dependency inversion gives the possibility to replace implementations. _But why would I do that_?

It obviously is a meaningful choice to separate the API from the actual assertion (domain) implementation: there can be multiple API styles and those styles are prone to change. In contrast, I cannot think of a reason why I would want to keep an assertion API but change the underlying matcher (domain) implementation. There is not much freedom for different implementations of a matcher. So why would I want to create a second implementation?

Architecture is always about balancing different goals. In this case, I think the separation leads to more complicated design and more code while bringing almost no benefit. So one option is to have _one_ implementation of the domain and no separation between interfaces and implementation.

## Implement dependency inversion differently

If we decide that the dependency inversion pattern is, in fact, a good choice, we could still implement it differently.

The main issues I see currently is that the builder projects together with the Java ServiceLoader logic and the custom glue code for Javascript create a lot of complexity and code, and thereby maintenance effort.

### A: Use dependency injection

The standard solution for dependency inversion is dependency injection. We could use a framework like [KodeIn](https://github.com/Kodein-Framework/Kodein-DI/), which would replace the builder projects entirely. There would be no more service loader logic, no more custom JavaScript glue code generation and no builders. Instead, there would only be an (interchangeable!) dependency injection module, which binds interfaces to implementations.

### B: Use Kotlin delegation

If we decide that neither removing dependency inversion nor using dependency injection is a good option, we could at least remove a lot of boilerplate code by removing the custom delegation implementation with Kotlin’s [Implementation by Delegation](https://kotlinlang.org/docs/reference/delegation.html#implementation-by-delegation).

The only “drawback” I see here is that the implementation functions would no longer be `inline`. However, from my understanding, the performance improvement of `inline` is neglectable in this case. Because any performance improvement (not creating a lambda object, not creating a generic bridge) will be removed in the next call because we call a non-inline method on an interface. 

**Code Example:**
This long class: 

```kotlin
object AnyAssertionsBuilder : AnyAssertions by anyAssertions {

    override inline fun <T : Any> toBe(subjectProvider: SubjectProvider<T>, expected: T): Assertion =
        anyAssertions.toBe(subjectProvider, expected)

    override inline fun <T> notToBe(subjectProvider: SubjectProvider<T>, expected: T) =
        anyAssertions.notToBe(subjectProvider, expected)

    override inline fun <T> isSame(subjectProvider: SubjectProvider<T>, expected: T) =
        anyAssertions.isSame(subjectProvider, expected)

    override inline fun <T> isNotSame(subjectProvider: SubjectProvider<T>, expected: T) =
        anyAssertions.isNotSame(subjectProvider, expected)

    override inline fun <T> toBeNull(subjectProvider: SubjectProvider<T>) =
        anyAssertions.toBeNull(subjectProvider)

    override inline fun <T : Any> toBeNullable(
        assertionContainer: Expect<T?>,
        type: KClass<T>,
        expectedOrNull: T?
    ) = anyAssertions.toBeNullable(assertionContainer, type, expectedOrNull)

    override inline fun <T : Any> toBeNullIfNullGivenElse(
        assertionContainer: Expect<T?>,
        type: KClass<T>,
        noinline assertionCreatorOrNull: (Expect<T>.() -> Unit)?
    ) = anyAssertions.toBeNullIfNullGivenElse(assertionContainer, type, assertionCreatorOrNull)

    override inline fun <T, TSub : Any> isA(assertionContainer: Expect<T>, subType: KClass<TSub>) =
        anyAssertions.isA(assertionContainer, subType)


    // everything below is deprecated functionality and will be removed with 1.0.0

    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("Switch from Assert to Expect and use toBeNullable; will be removed with 1.0.0")
    override inline fun <T : Any> isNullable(plant: AssertionPlantNullable<T?>, type: KClass<T>, expectedOrNull: T?) =
        anyAssertions.isNullable(plant, type, expectedOrNull)


    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("Switch from Assert to Expect and use toBeNullable; will be removed with 1.0.0")
    override inline fun <T : Any> isNotNull(
        plant: AssertionPlantNullable<T?>,
        type: KClass<T>,
        noinline assertionCreator: AssertionPlant<T>.() -> Unit
    ) = anyAssertions.isNotNull(plant, type, assertionCreator)

    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("Switch from Assert to Expect and use toBeNullable; will be removed with 1.0.0")
    override inline fun <T : Any> isNotNullBut(plant: AssertionPlantNullable<T?>, type: KClass<T>, expected: T) =
        anyAssertions.isNotNullBut(plant, type, expected)

    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("Switch from Assert to Expect and use toBeNullable; will be removed with 1.0.0")
    override inline fun <T : Any> isNullIfNullGivenElse(
        plant: AssertionPlantNullable<T?>,
        type: KClass<T>,
        noinline assertionCreatorOrNull: (AssertionPlant<T>.() -> Unit)?
    ) = anyAssertions.isNullIfNullGivenElse(plant, type, assertionCreatorOrNull)


    /**
     * Returns [AnyTypeTransformationAssertionsBuilder]
     * which inter alia delegates to the implementation of [AnyTypeTransformationAssertions].
     */
    @Suppress("DeprecatedCallableAddReplaceWith")
    @Deprecated("Switch from `Assert` to `Expect` use `ExpectImpl.changeSubject` or `ExpectImpl.feature.extract` instead; will be removed with 1.0.0")
    inline val typeTransformation
        get() = AnyTypeTransformationAssertionsBuilder
}
```

can be replaced by one line of code:

```kotlin
object AnyAssertionsBuilder : AnyAssertions by anyAssertions
```

**Comment by robstoll** [comment]
1. I moved it
2. I suggest that once we have a consent as here we create the ticket back in Atrium. Agreed?
3. I would also reduce domain-robstoll and domain-robstoll-lib to one module domain-impl => maybe this answers your open question?
   >  I still do not understand the difference between the domain and the assertion implementation. 
4. I think I now what you want to say with [R3 combinable, shareable implementation changes](https://github.com/robstoll/atrium/wiki/Requirements#r3-combinable-shareable-implementation-changes) but it is written in a manner I am not 100% sure (especially `publish` and `module` confuses me). Could you try to re-phrase it or provide an example? Maybe we should come up with a glossary as well? For me a module in the context of Atrium maps more or less to a jar but independent of the platform (e.g. atrium-core-api)
I have added R8 and R9 and will add more later on.

**Comment by jGleitz** [comment]
> I suggest that once we have a consent as here we create the ticket back in Atrium. Agreed?

Yes.

> I would also reduce domain-robstoll and domain-robstoll-lib to one module domain-impl => maybe this answers your open question? 

Maybe. As I said, I am beginning to lose overview. If we agree that this is a sensible step, let us do it and I will re-assess my understanding afterwards.

> I think I now what you want to say with R3 combinable, shareable implementation changes but it is written in a manner I am not 100% sure 

Oh I had great troubles wording this one. What I am trying to say is: Other entities (that are not the atrium maintainers themselves) can publish add-ons/implementation change modules.

For example: author A publishes a different implementation for `toBe`, author B a different implementation for `isA` and author C a different reporter implementation on maven central. Users should now be able to include all three modules (i.e. via gradle, possibly also by calling some `registerPlugin` method in atrium) and “it works”.

Does that help or only add more irritation?

>  I have added R8 and R9 and will add later on.

I really like how R7 and R8 interact with each other. I feel like they give a good definition of what atrium should contain. And they are a good reference for future discussions.

**Comment by robstoll** [comment]
closing this as domain builders as discussed here don't exist any more
