### ISSUE TITLE
move away from ResourceBundle based translation and properties

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#30]
due to two reasons:
- ResourceBundle is JVM specific
- the support of singular vs plural (or one vs two vs more vs many) is rather clunky and requires a lot of boilerplate code.

I have something like gettext in mind as replacement because:
- it is well know and used for a long time
- there are implementations for JVM, JS and obviously for native
- community driven translation is more likely to happen in the future due to online tools providing .po files

Other suggestions? There is a kotlin project which supports Android and iOS but not JS (have to look up the name later on).

**Comment by robstoll** [comment]
Added it to the 2.0.0 as this will most likely require a breaking change

**Comment by jGleitz** [comment]
Have we had a discussion about whether the translation feature is valuable enough to justify the development effort?

I definitely see where you are coming from in wanting to have this feature. However, do you know any real-world usage of the feature? Do the download numbers from Maven Central justify keeping it?

I think that the translation functionality adds complexity and maintenance effort. If people use it, that’s worth the effort. But I want to make sure that there are actual people using it. Testing is mostly done by engineers with good knowledge of English, which might suggest that there is not really a need for the feature (but I don’t know!)

**Comment by jGleitz** [comment]
I tried to get download numbers from Bintray, however, they only seem to report it for all atrium artefacts combined :disappointed:

**Comment by robstoll** [comment]
Just a quick input. If we follow the gettext approach, then contributors only provide the English text (which is used as key) and we translate on the fly. Which means we could get rid of atrium-translations etc.

**Comment by robstoll** [comment]
going to drop support for translation with 0.20.0, thus closing this issue
