### ISSUE TITLE
rename containsRegex to containsMatchIn?

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#35]
I have used containsRegex as it is a shortcut for `contains.atLeast(1).regex(...)`. However, Kotlin itself provides a method `containsMatchIn` on `Regex` (not on CharSequence though).
Thoughts?

**Comment by igorakkerman** [comment]
`matchIn` makes sense if you are already in the context of regex. `containsRegex` is self-explanatory.

**Comment by robstoll** [comment]
In the sense of we could provide a `Expect<Regex>.containsMatchIn` function?

**Comment by igorakkerman** [comment]
I meant that within the Kotlin `Regex` class, the other name makes sense. In Atrium, I would not change it to keep the code readable.

**Comment by robstoll** [comment]
good with me, closing it then :+1:
