### ISSUE TITLE
drop support for jdk6, jdk7, merge jdk8 extension into normal artifact

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#54]
Currently we have jdk8 functionality in an extra module. This makes things a bit more complicated and I am questioning if we really need to have it in a separate module. The reason why I did this is that depending on which android version you have to use you cannot use features from jdk8.

Newer android APIs include a lot more types from jdk8 as far as I can see (I am not an android dev). This guy still recommends using only stdlib on android projects for instance which would be contrary to what I guess: https://medium.com/@mbonnin/the-different-kotlin-stdlibs-explained-83d7c6bf293

and thus I suggest that we do the following:
- add a d8 compiler step with a d8 version from early 2018: https://github.com/robstoll/atrium/issues/167
- once we have it we can see if we can also compile the jdk8 module with the d8 compiler. If this is possible, then:
  - we can remove the jdk8 extension and integrate the functionality in the jvm module.
  - switch to kotlin stdlib-jdk8

Thoughts?

**Comment by jGleitz** [comment]
Is this really so much of an issue? Why can’t android devs use a more recent JDK for _tests_? The fact that the production code needs to be compatible with JDK 6 does not implicate that the test code also has to, does it?

**Comment by robstoll** [comment]
I guess so, at least there was this bug, showing that also in tests it uses d8 which could not deal with module-info.class back then: https://github.com/robstoll/atrium/issues/52

**Comment by robstoll** [comment]
Good news on this front. It seems the module-info.class bug was fixed by now in the d8 compiler and we are not far away from having a check which ensures that we don't use features from an Android SDK API level higher than the one we try to support. From a quick glance it seems we are able to support API level 24 which corresponds to Android 7.0 which was released in 2016.

Currently we use Files and LocalDate in the jdk8 extension which requires API level 26 which corresponds to Android 8.0.0. But it seems d8 changed also in this regard, it does no longer error if a type is not known (might be that was never the case and I was once bitten by the module-info.class bug). Which means we can not only drop support for jdk6 and jdk7 in 1.0.0 but also merge the jdk8 extension into the normal jar :man_dancing:
