### ISSUE TITLE
create good first issues for Path.isNotReadable/Writable

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#68]

**Comment by jGleitz** [comment]
I would like to challenge you the way you challenged me: Do you have as real-world use case for this?

Maybe we should not introduce these assertions for the same reasons we do not have `isExecutable`: YAGNI.

**Comment by robstoll** [comment]
See, this was a test and you have passed it confidently :wink: No, kidding... I was actually not 100% sure if we should add this functionality and your answer is enough for me. Let's wait until someone needs it.
