### ISSUE TITLE
Switch from Dependabot to Renovate

### ISSUE THREAD

**Issue by jGleitz** [robstoll/atrium-roadmap#69]
I have not made an in-depth analysis, but it seems that dependabot fails at updating some of the dependencies in this project. From my experience [renovate](https://github.com/renovatebot/renovate) can handle these cases without any issue. It also does not require a special dependency configuration. And it can update the gradle wrapper out of the box.

Since switching should be easy, I suggest we just change tools.

**Comment by robstoll** [comment]
moved it to atrium-roadmap as this needs more discussion

**Comment by jGleitz** [comment]
I have created a [test repository](https://github.com/jGleitz/renovate-multiple-gradle-projects-test) and, indeed, renovate will not create PRs for updates to independent gradle builds in subfolders. I can see from the logs that renovate finds all `build.gradle.kts` files, but only executes gradle once in the top level directory.

Ironically, renovate _can_ update the wrapper in all subprojects: https://github.com/jGleitz/renovate-multiple-gradle-projects-test/pull/2

**Comment by robstoll** [comment]
Hm... well, shall we go with a mixed approach? Thinking about it with a fresh mind, I think we should not run into problems as long as dependabot is not able to update gradlew and in the worst case we get two PRs. It's already nice if we don't have to update gradlew manually and detect problems early.

**Comment by robstoll** [comment]
Seems like renovate has troubles as well:
https://github.com/tegonal/atrium-ktor/pull/26

- seems like it is not be able to find tutteli-gradle-plugins
- wants to create several PRs for the same property update

**Comment by jGleitz** [comment]
> wants to create several PRs for the same property update

I don't think that is an issue becaus

1. Renovate will automatically close the other PRs after we merged one an Renovate sees that they are no longer needed.
1. We can configure dependencies that should be updated together to avoid the multiple PRs in the first place (we can probably even submit the config upstream)

> seems like it is not be able to find tutteli-gradle-plugins

That is strange (and bad)

**Comment by robstoll** [comment]
> We can configure dependencies that should be updated together to avoid the multiple PRs in the first place (we can probably even submit the config upstream)

Searched quickly but couldn't find anything. Do you already have an example (or a link)?

>  That is strange (and bad)

Indeed, seems like it is not considering all repositories and only searches in jcenter for the plugin -- even though it should be there as well, so maybe it was a glitch, we will see.

*Edit* No glitch, still same after a few more analysis, created an issue: https://github.com/renovatebot/renovate/issues/5376

**Comment by jGleitz** [comment]
You can do this using the [`groupName`](https://docs.renovatebot.com/configuration-options/#groupname) option in [`packageRules`](https://docs.renovatebot.com/configuration-options/#packagerules). [Here](https://github.com/renovatebot/presets/blob/master/packages/renovate-config-group/static-groups.js#L203) is an example that groups all Spring Boot dependencies into one PR (from renovate’s [pre-defined groups](https://github.com/renovatebot/presets/tree/master/packages/renovate-config-group)).

**Comment by jGleitz** [comment]
https://github.com/renovatebot/renovate/issues/5377

**Comment by robstoll** [comment]
trying it out now
