### ISSUE TITLE
`is instance of` only as failure hint?

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#7]
Currently we add it as assertion which means, if one would show not only failing assertion but all assertions then one would see something like:
```
expect: "hello hello"
◆ is instance of: String
◆ contains: "hello"

```

**Comment by robstoll** [comment]
The problem is that one can define a subject change without subsequent assertions:
```
expect(1 as Number).isA<Int>()
```
We would need a way to detect if at least one subsequent assertion is defined and if one of them fails

**Comment by jGleitz** [comment]
I have come across a lot of “is instance of” statements that were confusing to me because I never defined them explicitly. I quickly understood where they came from, but there are irritating still.

So I am very much in favour of this. It will improve usability.

**Comment by jGleitz** [comment]
> We would need a way to detect if at least one subsequent assertion is defined and if one of them fails

Couldn’t we just have two different types of type assertions? An implicit one which is only visible if it fails (even if we are showing succeeding assertions), and an explicit one which follows the normal settings of when to show it.

**Comment by robstoll** [comment]
Can you maybe share such a use case, would make the discussion easier. 
>  An implicit one which is only visible if it fails 

I am not sure what you mean, this sounds like a failure hint to me.

**Comment by jGleitz** [comment]
>  this sounds like a failure hint to me.

I am still not sure about the wording in atrium. It may very well be the case that what I have in mind is a failure hint.

My main point is this: To my understanding, atrium sometimes adds implicit “instance of”-statements (unfortunately, I can currently not find an example). These should behave differently (i.e. only add failure hints) than when the user explicitly uses the `isA`-assertion (in that case it should not only be a failure hint, imho, even if it is not the last assertion).

**Comment by jGleitz** [comment]
> Can you maybe share such a use case, would make the discussion easier.

I cannot remember when that was, but I remember the output contained a lot of unnecessary “instance of”-statements. I will report if I find it again.

**Comment by robstoll** [comment]
I see one place which most likely feel like an implicit "instance of" and others which might be seen as implicit as well. Following the functions incorporating a down-cast:

`toBe(expected: T?)`: down-casts the subject which is `T?` to `T` in case the passed `expected?` is not `null` -> this is most likely the one irritating you:
```
fun getInt(): Int? = null
expect(getInt()).toBe(2)
```
output:
```
expect: null
◆ is instance of type: Int (kotlin.Int) -- Class: Integer (java.lang.Integer)
  » to be: 2        (kotlin.Int <503195940>)
```
IMO the `is instance of type` does not add anything as we see the type of `2` as well in `(kotlin.Int <503195940>)` thus I suggest we remove it here entirely
<hr/>

notToBeNull: is a delegation to `isA<T>` where the subject was `T?` before
```
fun getList(): List<Int>? = null
expect(getList()).notToBeNull()
expect(getList()).notToBeNull { isEmpty() }
```
output:
```
expect: null
◆ is instance of type: List (kotlin.collections.List) -- Class: List (java.util.List)
```
```
expect: null
◆ is instance of type: List (kotlin.collections.List) -- Class: List (java.util.List)
  » is: empty
```
IMO worth it and I would keep it
<hr/>

Throwable.message: contains a notToBeNull check as message is of type `String?`

```
fun foo(): Int = throw IllegalArgumentException()
    expect {
        foo()
    }.toThrow<IllegalArgumentException> { messageContains("oh no") }
```
output:
```
expect: () -> kotlin.Int        (main$1 <1485891705>)
◆ ▶ thrown exception when called: java.lang.IllegalArgumentException
    ◾ is instance of type:  java.lang.IllegalArgumentException    // usually not shown as this one holds
    ◾ ▶ message: null
        ◾ is instance of type: String (kotlin.String) -- Class: String (java.lang.String)
          » contains: 
            ⚬ value: "oh no"        <1231799381>
              ⚬ ▶ number of occurrences: -1
                  ◾ is at least: 1
```
The user might not be aware of that message has type `String?` but would expect at least String. Thus discussable if the additional check `is instance of type: String` here is worth it. Kind of inconsistent to remove but in this case maybe OK?

<hr/>

toThrow: down-casts from Throwable to the expected type. Example see above, IMO it should not be a check but only a failure hint as there is no value in showing that IllegalArgumentException is a IllegalArgumentException

**Comment by jGleitz** [comment]
It is quite possible that the instance check in `toBe` was the one irritating me.

> IMO the is instance of type does not add anything as we see the type of 2 as well in (kotlin.Int <503195940>) thus I suggest we remove it here entirely

I agree completely.

<hr>

`notToBeNull`:

> IMO worth it and I would keep it

I would prefer if the output was “expect `null` not to be `null`”, but it’s fine

<hr>

Throwable.message:

Do all `contains` assertions include an `instanceOf` check for `String?`s? Because I would then make that a failure hint, _at least_. We could even remove it entirely because the message “expect: null contains "foo"” is already very clear on its own.

Apart from that, I would expect `messageContains` to work exactly like using the `contains` assertion on the `message` feature.

<hr>

I agree for `toThrow`.

**Comment by robstoll** [comment]
Ah... the example for `message` was maybe a bit misleading, it's not messageContains which contains the check but `message` which is just a shortcut for ` feature(Throwable::message) { notToBeNull(assertionCreator) }`

**Comment by jGleitz** [comment]
Ah I see. That’s fair, I guess. But I would still prefer if the failure head for `notToBeNull` would not talk about instance checks, but rather about values not being `null`.

**Comment by robstoll** [comment]
I disagree with changing the description to `not to be: null` as it removes important context IMO. Looking at the output of the example above with the new description:
```
expect: null
◆ not to be: null
  » is: empty
```
You can guess that the type of the subject was a List but is could also be any other collection type or Optional or any other type supporting isEmpty.
How about we change it to:
```
expect: null
◆ not to be: null 
  » is instance of: List (kotlin.collections.List) -- Class: List (java.util.List)
  » is: empty
```
Would that be a good compromise?

**Comment by jGleitz** [comment]
I see your point. And I like printing both, the „not to be:null“ and the type. However, can we put it into one line to make it less verbose? Like:

```
expect: null
◆ not to be: null (is instance of: List (kotlin.collections.List) -- Class: List (java.util.List))
  » is: empty
```

**Comment by robstoll** [comment]
How about: `not to be: null but instance of...` there are too many parentheses for my taste

**Comment by jGleitz** [comment]
Yes, that is good. Better than my suggestion.

**Comment by robstoll** [comment]
Created https://github.com/robstoll/atrium/issues/330 for `notToBeNull` and the other concerns where covered with https://github.com/robstoll/atrium/issues/298 and https://github.com/robstoll/atrium/issues/285
