### ISSUE TITLE
include Atrium in the presets of renovate

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#70]
Would be nice for Atrium users using Renovate, create a corresponding PR

https://github.com/renovatebot/presets/blob/master/packages/renovate-config-group/static-groups.js

**Comment by jGleitz** [comment]
I think the config should probably go here: https://github.com/renovatebot/presets/tree/master/packages/renovate-config-monorepo because atrium is a “monorepo” in their sense.

**Comment by robstoll** [comment]
I created an own repo because I did not have the time to checkout the project, adjust things, run generation etc.
https://github.com/robstoll/renovate-presets-jvm

That should do it as well as one would need to include the monorepo defined at renovatebot's place as well as far as I understand: https://github.com/robstoll/renovate-presets-jvm/blob/master/default.json
