### ISSUE TITLE
Remove kotlin bugs from readme?

### ISSUE THREAD

**Issue by robstoll** [robstoll/atrium-roadmap#73]
I saw now in different places that people hesitate to use Atrium as there are many bugs which restrict Atrium to progress in certain areas. 

Not like those Kotlin bugs wouldn't exist if one uses another assertion library. Those are Kotlin bugs after all but maybe it's something we should not show to the user.

The idea behind the list was that people would vote for those issues.

Thoughts?

**Comment by jGleitz** [comment]
I think it is valuable to have this documentation, but maybe it does not need to be as prominent as in the `README`. Maybe we can move it to the wiki?

in the long run, I think atrium needs a proper and shiny website. But that is already tracked in https://github.com/robstoll/atrium-roadmap/issues/32

**Comment by robstoll** [comment]
Good idea, let's move it to the wiki
